export enum PolusRpcTag {
    ChatVisibility = 0x80,
    SetRole = 0x82,
    CloseHud,
    Revive,
    PlaySound,
    Click,
    Use,
    SetHat,
    DespawnAllVents,
    SetOutline,
    SetOpacity,
    BeginAnimationPlayer,
    BeginAnimationCamera,
    EnterVent,
    ExitVent,
    SetCountingDown,
    ReportDeadBody = 0x90,
    SetAliveState = 0x92,
    DisplayKillAnimation,
    SetSpeedModifier,
    SetVisionModifier,
    SetRemainingEmergencies
}